### ISSUE TITLE
Python interpreter !

### ISSUE THREAD

**Issue by soufiane-fadil** [xemuliam/docker-zeppelin#1]
Dear all,

Cant' i use simple python on it ? Python isn't recognized ?
How can i solve it ?

**Comment by xemuliam** [comment]
Certainly you can :)
However you should at first install python packages into your docker container
Root cause for this exercise is quite simple: you should install additionally ~360MB
I try to minimize size of docker image thus if you need to use python please do below steps
Another way is rebuild docker image with some additional command from below

Just up your Zeppelin container
Then do next steps from docker console:
-  go inside container
```
$ docker exec -it your_container_name sh
```
- check Python version
```
/opt/zeppelin # python -V
sh: python: not found
```
- install python
```
/opt/zeppelin # apk add --update \
     python \
     python-dev \
     py-pip \
     build-base \
   && pip install py4j \
   && rm -rf /var/cache/apk/*
```
- check Python version again
```
/opt/zeppelin # python -V
Python 2.7.13
```

Now you are ready to test Python :)

Reatsrt Python interpreter in Zeppelin, create new note or paragraph and make simple test:
```
%python
print 1+1
```
Now press Shift + Enter

Enjoy! :)

P.S.: here is official documentation: https://zeppelin.apache.org/docs/latest/interpreter/python.html

**Comment by xemuliam** [comment]
I have added Python backend into the image
Please test and provide any issues.

Thanks in advance
